// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbCL1ikDF2wv1sHs21D9spXhng5cGihw0',
    appId: '1:520824265760:web:cfd7fc017a711a2135b045',
    messagingSenderId: '520824265760',
    projectId: 'tprb-a73e4',
    authDomain: 'tprb-a73e4.firebaseapp.com',
    storageBucket: 'tprb-a73e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1SRu0okS4RRAa9cILy5VBOIyz0CGkEoQ',
    appId: '1:520824265760:android:1c6de1965defefac35b045',
    messagingSenderId: '520824265760',
    projectId: 'tprb-a73e4',
    storageBucket: 'tprb-a73e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdk1jVMjdokWvWbvlqRCxzuQKj2N4K-zY',
    appId: '1:520824265760:ios:7698cb0e985a89cb35b045',
    messagingSenderId: '520824265760',
    projectId: 'tprb-a73e4',
    storageBucket: 'tprb-a73e4.firebasestorage.app',
    iosBundleId: 'com.example.tprb.RunnerTests',
  );
}
